### ISSUE TITLE
Proper release of v7.1.0 and v8.0.0

### ISSUE THREAD

**Issue by abogaart** [wicketstuff/wicket1.5-tree#5]
Hi there!

First of all, thanks for maintaining the good old Wicket1.5-tree, it made our recent upgrade to Wicket7 (and hopefully Wicket8 in the near future) a lot easier.

One thing we did lose some time on was realizing that the latest released version of the wicket-7.x branch is v7.1.0 and not v7.0.2, which contains a fix for a [blocking issue](https://github.com/wicketstuff/wicket1.5-tree/pull/4).

Although the artifacts for 7.1.0 and 8.0.0 have been deployed on Maven Central, they were never fully released (no git tag, no version bump in the POM files).

Is it possible to still do a proper release for both versions?

Thanks!

**Comment by martin-g** [comment]
Thanks for noticing this!
I've just pushed the missing parts for 8.0.0. 
I'm afraid the ones for 7.1.0 are lost.

**Comment by abogaart** [comment]
Thanks!
